<a href="https://colab.research.google.com/github/Praveenku32k/Python_40_works_day_to_day/blob/main/Bulding_a_Regression_MLP_Using_the_Sequential_API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
ROOT="/content/drive/MyDrive/Artifical_Neural_Network_class_Lab"

In [2]:
import os
os.chdir(ROOT)

In [3]:
os.getcwd()

'/content/drive/MyDrive/Artifical_Neural_Network_class_Lab'

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use("fivethirtyeight")

In [7]:
from sklearn.datasets import fetch_california_housing 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

housing=fetch_california_housing()

In [8]:
print(housing)

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]]), 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]), 'frame': None, 'target_names': ['MedHouseVal'], 'feature_names': ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude'], 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n-

In [11]:
X_train_full,X_test,y_train_full,y_test=train_test_split(housing.data,housing.target)

In [12]:
X_train,X_valid,y_train,y_valid=train_test_split(X_train_full,y_train_full)

In [13]:
X_train_full

array([[   3.7798    ,   27.        ,    4.76962457, ...,    2.90443686,
          34.22      , -118.57      ],
       [   3.7802    ,   10.        ,    5.0874036 , ...,    2.8714653 ,
          34.08      , -117.7       ],
       [   3.9375    ,   35.        ,    5.46524064, ...,    3.35828877,
          34.06      , -117.93      ],
       ...,
       [   2.5262    ,   21.        ,    3.02162162, ...,    3.98738739,
          33.78      , -118.27      ],
       [   2.0529    ,   43.        ,    3.84587814, ...,    2.3655914 ,
          32.72      , -117.14      ],
       [   3.1875    ,   18.        ,    5.04823748, ...,    3.09276438,
          38.62      , -122.87      ]])

In [14]:
X_test

array([[   8.4438    ,   16.        ,    7.51219512, ...,    3.31358885,
          34.22      , -118.64      ],
       [   3.5074    ,   37.        ,    5.12413793, ...,    3.36896552,
          36.59      , -119.4       ],
       [   3.6488    ,   21.        ,    4.15364917, ...,    1.82202305,
          34.02      , -118.42      ],
       ...,
       [   3.2143    ,   25.        ,    4.98929336, ...,    2.60171306,
          36.82      , -119.79      ],
       [   3.3824    ,   48.        ,    5.02754821, ...,    2.00550964,
          34.05      , -118.36      ],
       [   2.1424    ,   30.        ,    4.92783505, ...,    2.74484536,
          37.75      , -121.43      ]])

In [15]:
X_train

array([[   2.5       ,   43.        ,    3.46710526, ...,    2.41447368,
          37.96      , -121.26      ],
       [   3.2833    ,   38.        ,    5.56016598, ...,    3.17842324,
          37.95      , -122.34      ],
       [   3.4028    ,   52.        ,    4.42918455, ...,    3.70386266,
          37.76      , -122.41      ],
       ...,
       [   3.0833    ,   44.        ,    5.11670481, ...,    2.37070938,
          35.29      , -120.67      ],
       [   3.2708    ,   33.        ,    4.43190661, ...,    2.85603113,
          34.        , -118.42      ],
       [   5.5469    ,   22.        ,    4.7967033 , ...,    2.43406593,
          36.54      , -121.82      ]])

In [16]:
y_valid

array([1.   , 2.608, 1.49 , ..., 2.086, 0.483, 2.136])

In [17]:
y_test

array([3.9  , 0.938, 3.408, ..., 0.93 , 3.226, 1.25 ])

In [21]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_valid=scaler.transform(X_valid)
X_test=scaler.transform(X_test)

In [22]:
X_train

array([[-0.72071101,  1.13156167, -0.74111826, ..., -0.05539912,
         1.08696356, -0.845468  ],
       [-0.30376003,  0.73438204,  0.05099434, ...,  0.00331679,
         1.08227857, -1.38601834],
       [-0.24015012,  1.84648499, -0.37702222, ...,  0.04370121,
         0.9932637 , -1.42105401],
       ...,
       [-0.41022013,  1.21099759, -0.11683222, ..., -0.05876277,
        -0.16392956, -0.55016736],
       [-0.31041379,  0.33720242, -0.37599206, ..., -0.02146174,
        -0.76829365,  0.57597917],
       [ 0.90115536, -0.53659275, -0.23793584, ..., -0.05389329,
         0.42169456, -1.12575336]])

In [23]:
X_valid

array([[   2.2604    ,   43.        ,    3.67148014, ...,    3.01805054,
          37.77      , -122.21      ],
       [   6.0722    ,    4.        ,    5.85777778, ...,    2.99111111,
          33.66      , -117.59      ],
       [   4.4125    ,   12.        ,    6.86440678, ...,    3.3874092 ,
          35.41      , -119.19      ],
       ...,
       [   3.2622    ,   33.        ,    4.82405567, ...,    2.83797217,
          34.02      , -118.09      ],
       [   1.4934    ,   26.        ,    5.15730337, ...,    2.85018727,
          39.08      , -121.56      ],
       [   4.8516    ,   34.        ,    5.34343434, ...,    2.45454545,
          33.86      , -118.12      ]])

In [26]:
from tensorflow import keras
model=keras.models.Sequential([
                               keras.layers.Dense(30,activation="relu",input_shape=X_train.shape[1:]),
                               keras.layers.Dense(1)

])

In [27]:
model.compile(loss="sparse_categorical_crossentropy",
              optimizer="sgd",
              metrics=["accuracy"])


In [28]:
histroy=model.fit(X_train,y_train,epochs=30,
                  validation_data=(X_valid,y_valid))

Epoch 1/30
363/363 [==============================] - 4s 5ms/step - loss: nan - accuracy: 8.6133e-05 - val_loss: nan - val_accuracy: 0.0000e+00
Epoch 2/30
363/363 [==============================] - 1s 4ms/step - loss: nan - accuracy: 0.0000e+00 - val_loss: nan - val_accuracy: 0.0000e+00
Epoch 3/30
363/363 [==============================] - 2s 4ms/step - loss: nan - accuracy: 0.0000e+00 - val_loss: nan - val_accuracy: 0.0000e+00
Epoch 4/30
363/363 [==============================] - 2s 4ms/step - loss: nan - accuracy: 0.0000e+00 - val_loss: nan - val_accuracy: 0.0000e+00
Epoch 5/30
363/363 [==============================] - 1s 4ms/step - loss: nan - accuracy: 0.0000e+00 - val_loss: nan - val_accuracy: 0.0000e+00
Epoch 6/30
363/363 [==============================] - 1s 4ms/step - loss: nan - accuracy: 0.0000e+00 - val_loss: nan - val_accuracy: 0.0000e+00
Epoch 7/30
363/363 [==============================] - 2s 4ms/step - loss: nan - accuracy: 0.0000e+00 - val_loss: nan - val_accuracy: 0.0

In [29]:
mse_test=model.evaluate(X_test,y_test)

162/162 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.0000e+00


In [30]:
X_new=X_test[:3]

In [31]:
y_pred=model.predict(X_new)

In [32]:
print(X_new)

[[ 8.44380000e+00  1.60000000e+01  7.51219512e+00  1.00000000e+00
   1.90200000e+03  3.31358885e+00  3.42200000e+01 -1.18640000e+02]
 [ 3.50740000e+00  3.70000000e+01  5.12413793e+00  1.02068966e+00
   9.77000000e+02  3.36896552e+00  3.65900000e+01 -1.19400000e+02]
 [ 3.64880000e+00  2.10000000e+01  4.15364917e+00  1.04353393e+00
   1.42300000e+03  1.82202305e+00  3.40200000e+01 -1.18420000e+02]]


In [33]:
print(y_pred)

[[nan]
 [nan]
 [nan]]
